apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sandbox.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sandbox.serviceAccountName }}
  namespace: {{ .Values.sandbox.namespace }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: harness-sandbox-controller
  namespace: {{ .Values.sandbox.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harness-sandbox-controller
  namespace: {{ .Values.sandbox.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.sandbox.workerServiceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: harness-sandbox-controller
